#### Module 2: R Programming Basics  
#### PART - 1
- **Overview of R Programming**  
- **Environment Setup with R Studio**  
- **R Commands**  
- **Variables and Data Types**  
- **Control Structures**  
- **Data Structures in R:**  
  - Arrays  
  - Matrices  
  - Vectors  
  - Factors  
#### PART - 2
- **Functions in R**  
- **R Packages** 

# **Module 2: R Programming Basics**  

This module introduces the **fundamentals of R programming**, including its environment, basic syntax, data types, control structures, data structures, functions, and packages.  

---

## **1. Overview of R Programming**  

### **What is R?**  
R is an **open-source** and **highly extensible** programming language used for **statistical computing, data analysis, and data visualization**. It was developed by **Ross Ihaka and Robert Gentleman** at the University of Auckland, New Zealand.  

### **Why Learn R?**  
- **Statistical Computing**: Powerful built-in statistical tools.  
- **Data Manipulation**: Efficient handling of large datasets.  
- **Data Visualization**: Advanced plotting libraries like ggplot2.  
- **Machine Learning**: Used in AI and predictive analytics.  
- **Open Source**: Free to use and continuously updated by the community.  

### **Applications of R**  
- **Data Science & AI** (Predictive modeling, clustering, classification)  
- **Finance & Risk Analysis** (Stock market trends, portfolio management)  
- **Healthcare & Bioinformatics** (Genomic data analysis, medical research)  
- **Social Media Analysis** (Text mining, sentiment analysis)  
- **Statistical Research** (Hypothesis testing, ANOVA, regression analysis)  

---

## **2. Environment Setup with RStudio**  

### **Installing R and RStudio**  
1. **Download R** from [CRAN (Comprehensive R Archive Network)](https://cran.r-project.org/).  
2. **Download RStudio** from [RStudio official website](https://posit.co/download/rstudio-desktop/).  
3. **Install Additional Packages**:  
   ```r
   install.packages("ggplot2")
   install.packages("dplyr")
   ```

### **RStudio Interface Components**  
- **Source Pane** – Where scripts are written.  
- **Console** – Where commands are executed.  
- **Environment Pane** – Stores variables and objects.  
- **Files/Plots/Packages/Help Pane** – Manages files, visualizations, installed packages, and documentation.  

### **Running R Code in RStudio**  
- **Execute Line-by-Line**: `Ctrl + Enter`  
- **Run Entire Script**: `source("script.R")`  
- **Stop Execution**: `Esc`  

---

## **3. R Commands**  

### **Basic Commands**  
| Command | Description | Example |  
|---------|------------|---------|  
| `print()` | Outputs text or variables | `print("Hello, R!")` |  
| `cat()` | Concatenates and prints multiple values | `cat("Sum:", 5+3)` |  
| `c()` | Creates a vector | `c(1, 2, 3, 4, 5)` |  
| `seq()` | Generates a sequence | `seq(1, 10, by=2)` |  
| `rep()` | Repeats values | `rep(1:3, times=3)` |  
| `mean()` | Computes mean | `mean(c(10, 20, 30))` |  
| `sum()` | Computes sum | `sum(1, 2, 3, 4, 5)` |  

---

## **4. Variables and Data Types**  

### **Declaring Variables**  
```r
x <- 10
y = 20
z <- "Hello, R!"
```
R is **dynamically typed**, meaning variables do not need explicit type declarations.  

### **Data Types in R**  
| Data Type | Description | Example |  
|-----------|------------|---------|  
| **Numeric** | Decimal numbers | `x <- 5.6` |  
| **Integer** | Whole numbers | `y <- as.integer(10)` |  
| **Character (String)** | Text values | `name <- "Shreya"` |  
| **Logical (Boolean)** | TRUE or FALSE values | `flag <- TRUE` |  
| **Complex** | Complex numbers | `z <- 2+3i` |  
| **Raw** | Stores binary data | `r <- charToRaw("R")` |  

### **Checking Data Type**  
```r
class(x)  # Returns "numeric"
typeof(y) # Returns "integer"
```


---
---

# **5. Control Structures in R**  

Control structures in R **define the flow of execution** of a program. They help in **decision-making**, **looping**, and **controlling** iterations based on conditions.  

---

## **Types of Control Structures in R**  

1. **Conditional Statements** (`if`, `if-else`, `if-else if-else`, `ifelse()`, `switch`)  
2. **Looping Statements** (`for`, `while`, `repeat`)  
3. **Loop Control Statements** (`break`, `next`, `return`)  

---

## **1. Conditional Statements (Decision Making)**  

Conditional statements **execute different code** based on conditions.

### **1.1 if Statement**  
Executes a block **only if the condition is TRUE**.  

🔹 **Syntax:**  
```r
if (condition) {
    # Code to execute if condition is TRUE
}
```
🔹 **Example & Output:**  
```r
x <- 10
if (x > 5) {
    print("x is greater than 5")
}
```
**Output:**  
```
[1] "x is greater than 5"
```

---

### **1.2 if-else Statement**  
Executes one block **if the condition is TRUE**, otherwise executes another.  

🔹 **Syntax:**  
```r
if (condition) {
    # Code if condition is TRUE
} else {
    # Code if condition is FALSE
}
```
🔹 **Example & Output:**  
```r
x <- 3
if (x > 5) {
    print("x is greater than 5")
} else {
    print("x is not greater than 5")
}
```
**Output:**  
```
[1] "x is not greater than 5"
```

---

### **1.3 if-else if-else Statement**  
Checks **multiple conditions** in sequence.  

🔹 **Syntax:**  
```r
if (condition1) {
    # Code if condition1 is TRUE
} else if (condition2) {
    # Code if condition2 is TRUE
} else {
    # Code if all conditions are FALSE
}
```
🔹 **Example & Output:**  
```r
x <- 0
if (x > 0) {
    print("Positive")
} else if (x < 0) {
    print("Negative")
} else {
    print("Zero")
}
```
**Output:**  
```
[1] "Zero"
```

---

### **1.4 ifelse() Function (Vectorized If-Else)**  
✅ **Faster & used for vectors**  

🔹 **Syntax:**  
```r
ifelse(condition, value_if_TRUE, value_if_FALSE)
```
🔹 **Example & Output:**  
```r
x <- c(2, 7, 5, 1, 8)
result <- ifelse(x > 5, "Big", "Small")
print(result)
```
**Output:**  
```
[1] "Small" "Big" "Small" "Small" "Big"
```

---

### **1.5 switch Statement**  
✅ Used as a **simpler alternative to multiple if-else conditions**.  

🔹 **Syntax:**  
```r
switch(expression,
    "case1" = value1,
    "case2" = value2,
    "case3" = value3,
    ...
)
```
🔹 **Example & Output:**  
```r
day <- 3
result <- switch(day,
    "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"
)
print(result)
```
**Output:**  
```
[1] "Tuesday"
```

---

## **2. Looping Statements (Iteration)**  

Loops **repeat a block of code** multiple times until a condition is met.

### **2.1 for Loop**  
✅ Used when **iteration count is known**.  

🔹 **Syntax:**  
```r
for (variable in sequence) {
    # Code to execute in each iteration
}
```
🔹 **Example & Output:**  
```r
for (i in 1:5) {
    print(i)
}
```
**Output:**  
```
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
```

---

### **2.2 while Loop**  
✅ Used when **iteration count is unknown**.  

🔹 **Syntax:**  
```r
while (condition) {
    # Code to execute while condition is TRUE
}
```
🔹 **Example & Output:**  
```r
x <- 1
while (x <= 5) {
    print(x)
    x <- x + 1
}
```
**Output:**  
```
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
```

---

### **2.3 repeat Loop (Do-While Alternative)**  
✅ **Runs infinitely unless stopped by `break`**.  

🔹 **Syntax:**  
```r
repeat {
    # Code to execute
    if (condition) {
        break
    }
}
```
🔹 **Example & Output:**  
```r
x <- 1
repeat {
    print(x)
    x <- x + 1
    if (x > 5) {
        break
    }
}
```
**Output:**  
```
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
```

---

## **3. Loop Control Statements**  

### **3.1 break Statement**  
✅ **Terminates the loop immediately**.  

🔹 **Example & Output:**  
```r
for (i in 1:5) {
    if (i == 3) {
        break
    }
    print(i)
}
```
**Output:**  
```
[1] 1
[1] 2
```

---

### **3.2 next Statement**  
✅ **Skips the current iteration** and continues.  

🔹 **Example & Output:**  
```r
for (i in 1:5) {
    if (i == 3) {
        next
    }
    print(i)
}
```
**Output:**  
```
[1] 1
[1] 2
[1] 4
[1] 5
```

---

### **3.3 return Statement**  
✅ **Exits a function and returns a value**.  

🔹 **Example & Output:**  
```r
check_number <- function(x) {
    if (x > 0) {
        return("Positive")
    } else {
        return("Non-Positive")
    }
}
print(check_number(5))
print(check_number(-2))
```
**Output:**  
```
[1] "Positive"
[1] "Non-Positive"
```

---

## **🔹 Quick Comparison Table**
| Control Structure | Description | Example |
|------------------|------------|---------|
| `if` | Executes a block if condition is TRUE | `if (x > 0) print("Positive")` |
| `if-else` | Executes one block if TRUE, another if FALSE | `if (x > 0) print("Positive") else print("Negative")` |
| `ifelse()` | Vectorized if-else | `ifelse(x > 5, "Big", "Small")` |
| `switch()` | Selects a case based on an expression | `switch(x, "Red", "Blue", "Green")` |
| `for` Loop | Iterates over a sequence | `for (i in 1:5) print(i)` |
| `while` Loop | Runs until condition is FALSE | `while (x <= 5) { print(x); x <- x + 1 }` |
| `repeat` Loop | Runs indefinitely unless `break` is used | `repeat { if (x > 5) break }` |
| `break` | Exits a loop | `if (x == 3) break` |
| `next` | Skips an iteration | `if (x == 3) next` |
| `return` | Exits a function with a value | `return("Done")` |



---
---

# **6. Data Structures in R**  
Data structures in R are used to **store, organize, and manipulate data** efficiently.

---

## **6.1. Vector**  
A **homogeneous**, **one-dimensional** data structure that stores elements of the **same data type** (numeric, character, logical, etc.).

### **Creation**  
```r
vec <- c(1, 2, 3, 4, 5)  # Numeric vector
char_vec <- c("A", "B", "C")  # Character vector
log_vec <- c(TRUE, FALSE, TRUE)  # Logical vector
```
### **Operations**
```r
length(vec)  # Get length
vec[2]  # Access second element
vec * 2  # Element-wise multiplication
```
### **Output**
```
[1] 2
[1] 2 4 6 8 10
```

---

## **6.2. Matrix**  
A **homogeneous**, **two-dimensional** data structure arranged in **rows and columns**.

### **Creation**  
```r
mat <- matrix(1:9, nrow = 3, ncol = 3)
print(mat)
```
### **Output**
```
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
```
### **Operations**  
```r
mat[1,2]  # Access row 1, column 2
colSums(mat)  # Sum of each column
rowMeans(mat)  # Mean of each row
```
### **Output**
```
[1] 4
[1] 6 15 24
[1] 4 5 6
```

---

## **6.3. Array**  
A **multi-dimensional**, **homogeneous** data structure (more than 2 dimensions).

### **Creation**  
```r
arr <- array(1:12, dim = c(2,3,2))  # 2x3 matrix in 2 layers
print(arr)
```
### **Output**
```
, , 1
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2
     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12
```
### **Operations**  
```r
arr[1,2,1]  # First row, second column, first layer
```
### **Output**
```
[1] 3
```

---

## **6.4. List**  
A **heterogeneous**, **one-dimensional** collection of objects (vectors, matrices, data frames, etc.).

### **Creation**  
```r
lst <- list(name = "Shreya", age = 22, marks = c(80, 90, 85))
print(lst)
```
### **Output**
```
$name
[1] "Shreya"

$age
[1] 22

$marks
[1] 80 90 85
```
### **Operations**  
```r
lst$name  # Access by name
lst[[2]]  # Access second element
```
### **Output**
```
[1] "Shreya"
[1] 22
```

---

## **6.5. Data Frame**  
A **heterogeneous**, **two-dimensional** table-like structure (similar to a spreadsheet).

### **Creation**  
```r
df <- data.frame(Name = c("A", "B", "C"), Age = c(20, 21, 22), Score = c(85, 90, 95))
print(df)
```
### **Output**
```
  Name Age Score
1    A  20    85
2    B  21    90
3    C  22    95
```
### **Operations**  
```r
df$Age  # Access column
df[2, ]  # Access second row
```
### **Output**
```
[1] 20 21 22
  Name Age Score
2    B  21    90
```

---

## **6.6. Factor**  
A **categorical data** structure used to store distinct groups or levels.

### **Creation**  
```r
f <- factor(c("Low", "Medium", "High", "Low", "High"))
print(f)
```
### **Output**
```
[1] Low    Medium High   Low    High  
Levels: High Low Medium
```
### **Operations**  
```r
levels(f)  # Show categories
```
### **Output**
```
[1] "High"   "Low"    "Medium"
```

---

## **Enhanced Summary Table of Data Structures in R**
| Data Structure  | Type       | Dimension | Homogeneous? | Example Usage | Key Differences |
|----------------|-----------|-----------|--------------|--------------|----------------|
| **Vector**     | 1D Array  | 1         | ✅ Yes       | Numeric, Character | Fast operations, simplest structure |
| **Matrix**     | 2D Array  | 2         | ✅ Yes       | Mathematical operations | Fixed rows & columns, no mixed types |
| **Array**      | N-D Array | N         | ✅ Yes       | Multi-dimensional data | Extends matrices to 3D+ |
| **List**       | Collection | 1         | ❌ No       | Grouping different data types | Can hold anything (vectors, matrices, data frames) |
| **Data Frame** | Table     | 2         | ❌ No       | Dataset storage (rows & columns) | Supports mixed types per column |
| **Factor**     | Categorical | 1       | ✅ Yes       | Storing categorical variables | Used for classification tasks |

---

## **Key Takeaways**
- **Vectors, Matrices, and Arrays** store homogeneous data (same type).
- **Lists and Data Frames** allow heterogeneous data (different types).
- **Factors** are useful for categorical data (e.g., "High", "Low").
- **Data Frames** are widely used in **data analysis and machine learning**.
- **Lists** are flexible and can contain other data structures.
